name: setup-linux
description: Setup Miniconda and Java on linux
inputs:
  py_version:
    description: 'Python version'
    required: false
runs:
  using: composite
  steps:
  - uses: "./.github/actions/setup-miniconda"
    with:
      py_version: "${{ matrix.py_version }}"
  - uses: actions/setup-java@v4
    with:
      distribution: 'microsoft'
      java-version: '11'
  - name: Preparing environment - Other dependency
    shell: bash
    run: |-
      sudo apt-get update
      sudo apt-get install -y expect fish zsh