version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 10

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 10

