[pytest]
norecursedirs = 
  .nox                  # generated virtualenvs
  build                 # generated build directory
  contrib               # contributed plugins
  website               # No python code
  plugins               # tested separately under nox
  examples/plugins      # tested separately under nox
  examples              # tested separately under nox
  tests/standalone_apps # tested separately under nox
  tools                 # tools are tested individually

filterwarnings =
  error
  ; SQLAlchemy imported by old Optuna on Python 3.12+
  ignore:datetime.datetime.utcfromtimestamp\(\) is deprecated:DeprecationWarning:sqlalchemy.sql.sqltypes
  ; Remove when default changes
  ignore:.*Future Hydra versions will no longer change working directory at job runtime by default.*:UserWarning
  ; ResourceWarning warning unavoidably happens in the Optuna sqlite storage cleanup
  ignore:unclosed database in <sqlite3.Connection object at:ResourceWarning
