# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass, field
from omegaconf import MISSING


@dataclass
class UserConf:
    _target_: str = "configen.samples.my_module.User"
    _convert_: str = "all"
    _recursive_: bool = True
    age: int = MISSING
    name: str = MISSING


@dataclass
class AdminConf:
    _target_: str = "configen.samples.my_module.Admin"
    _convert_: str = "all"
    _recursive_: bool = True
    private_key: str = MISSING
    age: int = MISSING
    name: str = MISSING
