# @package _group_

# python logging configuration for tasks
version: 1
formatters:
  simple:
    format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: simple
    # relative to the job log directory
    filename: ${hydra.job.name}.log
root:
  level: INFO
  handlers: [console, file]

disable_existing_loggers: false
