hydra:
  sweep:
    dir: multirun
    subdir: ${hydra.job.override_dirname}/seed=${seed}
  job:
    config:
      override_dirname:
        exclude_keys:
          - seed

lr: 0.1
optimizer: adam
seed: 1
