name: setup-windows
description: Setup windows environment
inputs:
  py_version:
    description: 'Python version'
    required: false
runs:
  using: composite
  steps:
    - uses: "./.github/actions/setup-miniconda"
      with:
        py_version: "${{ matrix.py_version }}"
    - uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '11'
    - name: Preparing environment - Hydra
      shell: bash -el {0}
      run: |-
        pip install nox dataclasses --progress-bar off