# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass, field
from omegaconf import MISSING
from tests.test_modules import Color
from tests.test_modules import User
from typing import Dict


@dataclass
class DictValuesConf:
    _target_: str = "tests.test_modules.DictValues"
    dct: Dict[str, str] = MISSING
    enum_key: Dict[Color, str] = MISSING
    dataclass_val: Dict[str, User] = MISSING
    # [passthrough] passthrough_dict: Dict[str, LibraryClass]
    def_value: Dict[str, str] = field(default_factory={})
