# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass, field
from omegaconf import MISSING
from tests.test_modules import Color
from tests.test_modules import User
from typing import List


@dataclass
class ListValuesConf:
    _target_: str = "tests.test_modules.ListValues"
    lst: List[str] = MISSING
    enum_lst: List[Color] = MISSING
    # [passthrough] passthrough_list: List[LibraryClass]
    dataclass_val: List[User] = MISSING
    def_value: List[str] = field(default_factory=[])
