# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass, field
from omegaconf import MISSING


@dataclass
class PeskySentinelUsageConf:
    _target_: str = "tests.test_modules.PeskySentinelUsage"
    # [passthrough] foo: Any = <I am a pesky sentinel>
