# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass, field
from omegaconf import MISSING
from typing import Any
from typing import Tuple


@dataclass
class TuplesConf:
    _target_: str = "tests.test_modules.Tuples"
    t1: Tuple[float, float] = MISSING
    t2: Any = (1, 2, 3)
    t3: Tuple[float, ...] = (0.1, 0.2, 0.3)
