log_user 0
set timeout 5
set env(PS1) >
spawn bash --norc
expect >

set in_line [lindex $argv 1]
set len [expr [string length $in_line] - 1]
set line [string range $in_line 5 $len]
set num_tabs [lindex $argv 2]
send "eval \"\$([lindex $argv 0] -sc install=bash)\"\r"
expect >

set command "[lindex $argv 0] $line"
while {$num_tabs > 0} {
    incr num_tabs -1
    append command "\t"
}

send $command
foreach arg [lrange $argv 3 end] {
    expect {
        "$arg" {continue}
        timeout {puts "error matching $arg"; exit 1}
    }
}