hydra:
  run:
    dir: ./outputs/custom/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: /checkpoint/${env:USER}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.name}
    subdir: ${hydra.job.num}_${hydra.job.override_dirname}